main: com.noah.pws.PerWorldServer
name: PerWorldServer
author: Struck713
description: Separate your chat and tab list on a per world basis!
api-version: 1.13
version: 4.1

commands:
  pws:
    aliases: ['perworldserver']
    permission: 'pws.admin'
    description: 'Use this command to create, delete and modify suites.'

permissions:
  pws.*:
    default: op
    description: 'Gives user access to all of the PWS commands.'
    children:
      - pws.admin
  pws.admin:
    default: op
    description: 'Allows user to use the ''/suite'' command.'